### ISSUE TITLE
RESULT

### ISSUE THREAD

**Issue by yanxon** [yanxon/thermal_expansion#1]
Hi @timfrol,

Please check out this repo :)

**Comment by timfrol** [comment]
@yanxon 

Looking good Howard! Great work! 
Did you compare it with my calculations? They all agree I assume?

**Comment by yanxon** [comment]
@timfrol 

They are somewhat the same. I only run them 100k steps rather than 900k.

**Comment by timfrol** [comment]
@yanxon 

just to continue our practice, lets do Cu

here are my results

0 1
100  1.00150338
200  1.00304805
300  1.00468493
400  1.00630743
500  1.00809758
600  1.00978187
700  1.01168907
800  1.01350613
900  1.01569069
1000  1.01779014
1100  1.02006927
1200  1.02253427
1300  1.02520674
1327 1.0259081143371

Please plot mine and yours to compare. They may be slightly different depending on the system size, and as you pointed out the simulation time. For Pd simulations we would like to get converged values. Dunno if 900k is absolutely necessary, but check how your data converges with the number of steps. 

great stuff!

**Comment by yanxon** [comment]
@timfrol 

Is that normalized lattice?

**Comment by timfrol** [comment]
@yanxon 

this is the scaling factor relative to the 0K lattice parameter. 

so alat_300K=alat_0K* 1.00468493

**Comment by yanxon** [comment]
@timfrol 


![xyz](https://github.com/yanxon/thermal_expansion/blob/master/comparison.png)

**Comment by timfrol** [comment]
@yanxon 
excellent!
